# Site settings
title: Joey Litalien
email: joey.litalien@gmail.com
email_display: joey [dot] litalien [at] gmail [dot] com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joeylitalien.github.io" # the base hostname & protocol for your site
twitter_username:  joeylitalien
mastodon_username:  joeylitalien
github_username: joeylitalien
googlescholar_username: 511IDxQAAAAJ
mathstack_username: 49109/hubble
linkedin_username: joeylitalien
spotify_username: 12162861472

# Build settings
markdown: kramdown
collections:
    publications:
        output: true
    projects:
        output: true
    news:
        output: true
