# Site settings
title: Joey Litalien
email: joey.litalien@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joeylitalien.github.io" # the base hostname & protocol for your site
twitter_username:  joeylitalien
github_username:  joeylitalien
mathstack_username: 49109/hubble
linkedin_username: joey-litalien
spotify_username: 12162861472

# Build settings
markdown: kramdown
collections:
    projects:
        output: true
    news:
        output: true
